[package]
name = "dd_wcag"
version = "0.8.0"
edition = "2024"

[workspace]
members = ["crates/ldnddev_theme"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[dependencies]
anyhow = "1.0.101"
crossterm = "0.29"
palette = { version = "0.7.6", default-features = false, features = ["std"] }
ratatui = { version = "0.30", default-features = false, features = ["crossterm"] }
rfd = { version = "0.15", default-features = false, features = ["xdg-portal", "async-std"] }
ldnddev_theme = { path = "crates/ldnddev_theme" }
